# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BtRequest.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='BtRequest.proto',
  package='',
  serialized_pb=_b('\n\x0f\x42tRequest.proto\"\xde\x01\n\tBtRequest\x12\'\n\x07request\x18\x01 \x02(\x0e\x32\x16.BtRequest.RequestType\x12\x12\n\ndeviceName\x18\x02 \x01(\t\x12\x11\n\ttopicName\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\"s\n\x0bRequestType\x12\x10\n\x0cLIST_DEVICES\x10\x01\x12\x0f\n\x0bLIST_TOPICS\x10\x02\x12\r\n\tSUBSCRIBE\x10\x03\x12\x0f\n\x0bUNSUBSCRIBE\x10\x04\x12\x0e\n\nWRITE_DATA\x10\x05\x12\x11\n\rHEALTH_STATUS\x10\x06')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_BTREQUEST_REQUESTTYPE = _descriptor.EnumDescriptor(
  name='RequestType',
  full_name='BtRequest.RequestType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LIST_DEVICES', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LIST_TOPICS', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUBSCRIBE', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNSUBSCRIBE', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WRITE_DATA', index=4, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HEALTH_STATUS', index=5, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=127,
  serialized_end=242,
)
_sym_db.RegisterEnumDescriptor(_BTREQUEST_REQUESTTYPE)


_BTREQUEST = _descriptor.Descriptor(
  name='BtRequest',
  full_name='BtRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request', full_name='BtRequest.request', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='deviceName', full_name='BtRequest.deviceName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='topicName', full_name='BtRequest.topicName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='BtRequest.data', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _BTREQUEST_REQUESTTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=242,
)

_BTREQUEST.fields_by_name['request'].enum_type = _BTREQUEST_REQUESTTYPE
_BTREQUEST_REQUESTTYPE.containing_type = _BTREQUEST
DESCRIPTOR.message_types_by_name['BtRequest'] = _BTREQUEST

BtRequest = _reflection.GeneratedProtocolMessageType('BtRequest', (_message.Message,), dict(
  DESCRIPTOR = _BTREQUEST,
  __module__ = 'BtRequest_pb2'
  # @@protoc_insertion_point(class_scope:BtRequest)
  ))
_sym_db.RegisterMessage(BtRequest)


# @@protoc_insertion_point(module_scope)
