# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BtReply.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='BtReply.proto',
  package='',
  serialized_pb=_b('\n\rBtReply.proto\"\xf3\x03\n\x07\x42tReply\x12%\n\x07request\x18\x01 \x02(\x0e\x32\x14.BtReply.RequestType\x12\x0f\n\x07\x64\x65vices\x18\x02 \x03(\t\x12\x0e\n\x06topics\x18\x03 \x03(\t\x12\x16\n\x0etopicsSelected\x18\x04 \x03(\x08\x12\x0e\n\x06upTime\x18\x05 \x01(\x04\x12\x1c\n\x14\x63onnectedDeviceCount\x18\x06 \x01(\r\x12\x18\n\x10\x61\x63tiveTopicCount\x18\x07 \x01(\r\x12\x13\n\x0b\x63urrentTime\x18\x08 \x01(\x04\x12\x16\n\x0e\x63onfigFileName\x18\t \x01(\t\x12\x1a\n\x12\x63onfigFileDateTime\x18\n \x01(\x04\x12.\n\x0c\x64\x65vicesState\x18\x0b \x03(\x0e\x32\x18.BtReply.ConnectionState\x12\x13\n\x0bmobiVersion\x18\x0c \x01(\t\"s\n\x0bRequestType\x12\x10\n\x0cLIST_DEVICES\x10\x01\x12\x0f\n\x0bLIST_TOPICS\x10\x02\x12\r\n\tSUBSCRIBE\x10\x03\x12\x0f\n\x0bUNSUBSCRIBE\x10\x04\x12\x0e\n\nWRITE_DATA\x10\x05\x12\x11\n\rHEALTH_STATUS\x10\x06\"=\n\x0f\x43onnectionState\x12\r\n\tCONNECTED\x10\x01\x12\x10\n\x0c\x44ISCONNECTED\x10\x02\x12\t\n\x05\x45RROR\x10\x03')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_BTREPLY_REQUESTTYPE = _descriptor.EnumDescriptor(
  name='RequestType',
  full_name='BtReply.RequestType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LIST_DEVICES', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LIST_TOPICS', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUBSCRIBE', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNSUBSCRIBE', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WRITE_DATA', index=4, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HEALTH_STATUS', index=5, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=339,
  serialized_end=454,
)
_sym_db.RegisterEnumDescriptor(_BTREPLY_REQUESTTYPE)

_BTREPLY_CONNECTIONSTATE = _descriptor.EnumDescriptor(
  name='ConnectionState',
  full_name='BtReply.ConnectionState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CONNECTED', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DISCONNECTED', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=456,
  serialized_end=517,
)
_sym_db.RegisterEnumDescriptor(_BTREPLY_CONNECTIONSTATE)


_BTREPLY = _descriptor.Descriptor(
  name='BtReply',
  full_name='BtReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request', full_name='BtReply.request', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='devices', full_name='BtReply.devices', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='topics', full_name='BtReply.topics', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='topicsSelected', full_name='BtReply.topicsSelected', index=3,
      number=4, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='upTime', full_name='BtReply.upTime', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='connectedDeviceCount', full_name='BtReply.connectedDeviceCount', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='activeTopicCount', full_name='BtReply.activeTopicCount', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='currentTime', full_name='BtReply.currentTime', index=7,
      number=8, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='configFileName', full_name='BtReply.configFileName', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='configFileDateTime', full_name='BtReply.configFileDateTime', index=9,
      number=10, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='devicesState', full_name='BtReply.devicesState', index=10,
      number=11, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mobiVersion', full_name='BtReply.mobiVersion', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _BTREPLY_REQUESTTYPE,
    _BTREPLY_CONNECTIONSTATE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=517,
)

_BTREPLY.fields_by_name['request'].enum_type = _BTREPLY_REQUESTTYPE
_BTREPLY.fields_by_name['devicesState'].enum_type = _BTREPLY_CONNECTIONSTATE
_BTREPLY_REQUESTTYPE.containing_type = _BTREPLY
_BTREPLY_CONNECTIONSTATE.containing_type = _BTREPLY
DESCRIPTOR.message_types_by_name['BtReply'] = _BTREPLY

BtReply = _reflection.GeneratedProtocolMessageType('BtReply', (_message.Message,), dict(
  DESCRIPTOR = _BTREPLY,
  __module__ = 'BtReply_pb2'
  # @@protoc_insertion_point(class_scope:BtReply)
  ))
_sym_db.RegisterMessage(BtReply)


# @@protoc_insertion_point(module_scope)
